### ISSUE TITLE
comments from MoveApps

### ISSUE THREAD

**Issue by andreakoelzsch** [dmpstats/Workflow-Product-Retriever#3]
Hi Bruno,
Thanks for making this App, it is super-useful for MoveApps in general!
I have some questions and comments:

1. Beware that the API of MoveApps always refers to a Workflow Instance, so that also the title should be the Workflow Instance Title, and not the Workflow Title as you suggest in your setting "Target Workflow Title". You will not need the workflow instance title, but I see your point in requesting it.

2. The new object is appended in a list named appended products. I think that this might make it more complicated for future App use. But I am not 100% sure how to improve it. If your App allowed to only upload and integrate location data (move2_loc) then, I would suggest to call this "appended_products" data, like in the other Apps and append it to the data, in case the App is not a starting App. Do you primarily make this App to load data that is not the same as the App input time (move2_loc)? How do you deal with txt and csv files? Do you translate them to move2? This might be something worth to shortly meet about at some point.

3. If this App is supposed to be able to be a starting App, we have to integrate it as that to MoveApps via the backbone. Let me know if you require that, once the App is finished. If you submit it as a normal App, you can only add it to workflows that already have started with one of the "starting" Apps (Movebank, Cloud Upload).

4. In your part "Output Data" in the readme.md, you provide some code for exploration of the appended product. Is this meant for other App developers? It is definitely too much for App users that simply want to use the App without understanding the code. Might be worth to clarify that there.

I am looking forward to have this App running :)

**Comment by bcaneco** [comment]
Hi @andreakoelzsch,
Just a quick update: App has been released and submitted to MoveApps (as you probably noticed already). It addresses your comments regarding the readme file, as well as the added option catering for input data being specified as either `NULL` or a `move2` object.

Do you need anything else from us in order to add it to your list of Apps to be integrated as starting Apps?

Thank you so much for all your suggestions and for the chat we had last week!

**Comment by andreakoelzsch** [comment]
Hi @bcaneco Thanks for the App submission. For integrating it as a starting App, the App has to be added fully to the system. That means, if you are done with your testing, please go to the App in "My Apps" and "approve" it. Thanks!

**Comment by bcaneco** [comment]
Hi @andreakoelzsch,

Thanks for accepting the submission of the various patch versions of the App - strongly benefiting from the newly implemented Trial functionality! 😄 

This last patch was needed due to an apparent forced conversion from NULL to `0` in the Apps Settings GUI for one of the input parameters. As it's shown below, the default value for `app_pos` is specified to be `null` on the appspecs.json script

https://github.com/dmpstats/Workflow-Product-Retriever/blob/a165c47f969736b7d3a2070b56a61bf8692b896f/appspec.json#L28-L34

However, when the App is installed in the Workflow and the Settings are called, the entry field for that input is defaulting to 0.

![Screenshot 2023-11-28 163733](https://github.com/dmpstats/Workflow-Product-Retriever/assets/12933586/41442bbd-4028-4446-9eb3-e7d0884017ce)

This behaviour doesn't seem to happen in string-type inputs...

Is there a way to force/convince the Settings GUI to take the null default as a valid integer input?

Thank you!

**Comment by andreakoelzsch** [comment]
Hi @bcaneco,
Interesting that you point this one out. I have just discussed with out developer to fix this bug (as that is what it is), yesterday. So, then it will be possible to have null as a valid input (namely the empty one, where we add some small hint about it). It should become life next week, I hope.
Thnaks for keeping so close with us :)

**Comment by bcaneco** [comment]
@andreakoelzsch  - whoop whoop! 

![Screenshot 2023-11-29 134350](https://github.com/dmpstats/Workflow-Product-Retriever/assets/12933586/fec64a39-68b3-4ddb-adc3-3b42b627753f)

Thank you for the prompt fix!! 🙂

**Comment by andreakoelzsch** [comment]
Great that you have found it! Was indeed a coincidence, but nice that it serves many
